name: Snyk Scan for Java App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'   # Java version
        distribution: 'adoptopenjdk'   # Specify the JDK distribution

    - name: Install dependencies
      run: |
        ./mvnw install  # Use your build tool, such as Maven or Gradle

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Authenticate Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Snyk Test
      run: snyk test --all-projects

    - name: Snyk Monitor
      run: snyk monitor --all-projects
