name: Snyk Vulnerability Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk:
    name: Snyk Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Adjust based on your project’s Java version

      # Step 3: Install Snyk CLI
      - name: Install Snyk CLI
        uses: snyk/actions/setup@a93b4b27f0f2d8457d4c3439ba83d1ddbd40e0d6
        with:
          token: ${{ secrets.SNYK_TOKEN }}

      # Step 4: Run Snyk Test
      - name: Run Snyk test
        run: snyk test --all-projects
